CREATE TABLE users (
  USER_ID INTEGER NOT NULL,
  USERNAME VARCHAR(45) UNIQUE NOT NULL,
  FIRST_NAME VARCHAR(45) NOT NULL,
  LAST_NAME VARCHAR(45) NOT NULL,
  EMAIL VARCHAR(45) NOT NULL,
  PASSWORD VARCHAR(45) NOT NULL,
  ENABLED  BOOLEAN NOT NULL,
  PRIMARY KEY (USER_ID)
);

CREATE TABLE user_roles (
  USER_ROLE_ID INTEGER NOT NULL,
  USER_ID INTEGER NOT NULL,
  AUTHORITY VARCHAR(45) NOT NULL,
  PRIMARY KEY (USER_ROLE_ID),
  FOREIGN KEY (USER_ID) REFERENCES users (USER_ID)
);


INSERT INTO users (USER_ID, USERNAME, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, ENABLED)
VALUES (100, 'a', 'JOHN','DOE','fake@fake.com','0cc175b9c0f1b6a831c399e269772661', TRUE);

INSERT INTO user_roles (USER_ROLE_ID, USER_ID,AUTHORITY)
VALUES (1, 100, 'ROLE_USER');



